[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm run start"
  port = 3000
  targetPort = 3000
  publish = "build"
  functions = "netlify/functions"
  functionsPort = 9999 