name: Email Notification

on:
  repository_dispatch:
    types: [email_received]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: New Introduction Game Response
          body: |
            A new response has been received from the Introduction Game!

            Email: ${{ github.event.client_payload.email }}
            Action: ${{ github.event.client_payload.action }}

            Time: ${{ github.event.client_payload.timestamp }}
          to: saemmilee1231@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/html
